call plug#begin('~/.vim/plugged')
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
"Plug 'ycm-core/YouCompleteMe'
Plug 'chriskempson/base16-vim'

call plug#end()

" Plugin configuration
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#branch#enabled = 1
let g:airline_powerline_fonts = 1
let g:airline_theme='wombat'

set autoindent
set number
set whichwrap+=<,>,h,l,[,]
set incsearch
set clipboard=unnamedplus
set virtualedit=onemore
set hidden
set exrc
set secure
set colorcolumn=110
set laststatus=2
set splitbelow
set splitright
if has('mouse')
	set mouse=a
endif

" GUI settings

highlight ColorColumn ctermbg=darkgray
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$/
set background=dark
let base16colorspace=256
colorscheme base16-tomorrow-night
syntax on
hi Normal ctermbg=NONE
set termguicolors

" Jump to last position
if has("autocmd")
	au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

" Strip trailing whitespace on write
autocmd BufWritePre * :%s/\s\+$//e

" I want <C-x> to close buffers, not windows. But the last buffer I close will
" leave an empty window that I then have to manually close. This fixes that.
function! CountListedBuffers()
	let cnt = 0
	for nr in range(1,bufnr("$"))
		if buflisted(nr) && ! empty(bufname(nr)) || getbufvar(nr, '&buftype') ==# 'help'
			let cnt += 1
		endif
	endfor
	return cnt
endfunction
function! QuitIfLastBuffer()
	if CountListedBuffers() == 1
		:q
	endif
endfunction
autocmd BufDelete * :call QuitIfLastBuffer()

" I am a Windows goon. I like my standard keybindings. A *LOT*.
source $VIMRUNTIME/mswin.vim
behave mswin

snoremap <Del> <C-g>"_d
snoremap <C-x> <Del>

snoremap <C-c> <C-g>y
snoremap <C-v> <C-g>"_dgP
snoremap <Tab> <C-g>1>
snoremap <S-Tab> <C-g>1<
snoremap <C-s> <Esc><C-s>

map <Esc>[5A <C-Up>
map <Esc>[5B <C-Down>
map <Esc>[5C <C-Right>
map <Esc>[5D <C-Left>
map! <Esc>[5A <C-Up>
map! <Esc>[5B <C-Down>
map! <Esc>[5C <C-Right>
map! <Esc>[5D <C-Left>

nnoremap <C-c> <C-g>yy
nnoremap <C-v> <C-g>gP
nnoremap <C-d> <C-g>dd
nnoremap <Tab> V1><Esc>
nnoremap <S-Tab> V1<<Esc>
nnoremap <C-s> :w<CR>
nnoremap <C-x> :bd<CR>
nnoremap <C-q> :q!<CR>
nnoremap <CR> i<CR><Esc>
nnoremap <BS> i<BS><Esc>`^
nnoremap <Space> i<Space><Esc>`^
nnoremap <End> <End><Right>
nnoremap <C-e> :bn<CR>
execute "set <M-,>=\e,"
nnoremap <M-,> :bp<CR>
nnoremap <M-.> :bn<CR>
nnoremap <C-Up> {
nnoremap <C-Down> }
nnoremap <C-Left> b<Left>
nnoremap <C-Right> e<Right>

inoremap <C-c> <Esc>`^<C-g>yyi
inoremap <C-v> <Esc>`^gPi
inoremap <C-d> <Esc>`^<C-g>"_ddi
inoremap <C-x> <Esc>`^<C-g>ddi
inoremap <S-Tab> <Esc>`^V1<<Esc>i
inoremap <C-s> <Esc>`^:w<CR>
inoremap <C-q> <Esc>:q!<CR>
inoremap <C-e> <C-o>:bn<CR>
inoremap <M-,> <C-o>:bp<CR>
inoremap <M-.> <C-o>:bn<CR>
inoremap <C-Up> <C-o>{
inoremap <C-Down> <C-o>}
